esphome:
  name: lab-radar
  friendly_name: Lab Radar

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: esp-idf

# Send logs over native USB (frees UART0 pins)
logger:
  baud_rate: 0

# Home Assistant API
api:
  encryption:
    key: "9VDH8Uu50w4UTvIP3mJLW/6rbLK/krheUb593nXNFRQ="

ota:
  - platform: esphome
    password: "cd670c3433fac1c8f84d12366956b6a8"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "Lab-Radar Fallback Hotspot"
    password: "Kx6876ZIzHrl"

# ---------------------------------------------------------------------------------
# What you’ll see
# Presence should trigger within ~2 m of the sensor (bed area).
# Far movement (hallway) should not trigger.
# “Still Target” should stay detected while someone lies still; it will clear ~45 s after they leave.
# ---------------------------------------------------------------------------------

captive_portal:

# Built-in web UI
web_server:
  port: 80
  include_internal: true

# ---------------------------------------------------------------------------------

# Status LED (moved off strapping pin)
light:
  - platform: binary
    name: "Blue Status Light"
    output: light_output
    id: led_light
    restore_mode: ALWAYS_OFF

output:
  - platform: gpio
    pin: GPIO3
    id: light_output

# --- LD2410 UART on dedicated pins ---
uart:
  id: ld2410_uart
  tx_pin: GPIO5          # ESP TX -> LD2410 RX
  rx_pin: GPIO4          # ESP RX <- LD2410 TX
  baud_rate: 256000
  rx_buffer_size: 512
  parity: NONE
  stop_bits: 1

ld2410:
  uart_id: ld2410_uart
  id: ld2410_comp

# ===========================
# Controls (give IDs so we can set them at boot)
# ===========================
select:
  - platform: ld2410
    distance_resolution:
      name: distance resolution
      id: sel_distance_resolution
    baud_rate:
      name: baud rate
      id: sel_baud
    light_function:
      name: light function
      id: sel_light_function
    out_pin_level:
      name: out pin level
      id: sel_out_pin_level

button:
  - platform: ld2410
    factory_reset:
      name: "factory reset"
      id: btn_factory_reset
    restart:
      name: "restart"
      id: btn_restart
    query_params:
      name: query params
      id: btn_query

number:
  - platform: ld2410
    timeout:
      name: timeout
      id: num_timeout
    max_move_distance_gate:
      name: max move distance gate
      id: num_max_move_gate
    max_still_distance_gate:
      name: max still distance gate
      id: num_max_still_gate

    g0:
      move_threshold:
        name: g0 move threshold
        id: g0_move_th
      still_threshold:
        name: g0 still threshold
        id: g0_still_th
    g1:
      move_threshold:
        name: g1 move threshold
        id: g1_move_th
      still_threshold:
        name: g1 still threshold
        id: g1_still_th
    g2:
      move_threshold:
        name: g2 move threshold
        id: g2_move_th
      still_threshold:
        name: g2 still threshold
        id: g2_still_th
    g3:
      move_threshold:
        name: g3 move threshold
        id: g3_move_th
      still_threshold:
        name: g3 still threshold
        id: g3_still_th
    g4:
      move_threshold:
        name: g4 move threshold
        id: g4_move_th
      still_threshold:
        name: g4 still threshold
        id: g4_still_th
    g5:
      move_threshold:
        name: g5 move threshold
        id: g5_move_th
      still_threshold:
        name: g5 still threshold
        id: g5_still_th
    g6:
      move_threshold:
        name: g6 move threshold
        id: g6_move_th
      still_threshold:
        name: g6 still threshold
        id: g6_still_th
    g7:
      move_threshold:
        name: g7 move threshold
        id: g7_move_th
      still_threshold:
        name: g7 still threshold
        id: g7_still_th
    g8:
      move_threshold:
        name: g8 move threshold
        id: g8_move_th
      still_threshold:
        name: g8 still threshold
        id: g8_still_th

    light_threshold:
      name: light threshold
      id: num_light_th

text_sensor:
  - platform: ld2410
    version:
      name: "presence sensor version"
    mac_address:
      name: "presence sensor mac address"

switch:
  - platform: ld2410
    engineering_mode:
      name: "engineering mode"
    bluetooth:
      name: control Bluetooth
      id: sw_bluetooth

sensor:
  - platform: internal_temperature
    name: "Internal Temperature"

  - platform: ld2410
    moving_distance:
      name: "Moving distance (cm)"
      filters: [ { throttle: 1.5s } ]
    still_distance:
      name: "Still Distance (cm)"
      filters: [ { throttle: 1.5s } ]
    moving_energy:
      name: "Move Energy (%)"
      filters: [ { throttle: 1.5s } ]
    still_energy:
      name: "Still Energy (%)"
      filters: [ { throttle: 1.5s } ]
    detection_distance:
      name: "Distance Detection (cm)"
      filters: [ { throttle: 1.5s } ]

    g0:
      move_energy:   { name: g0 move energy }
      still_energy:  { name: g0 still energy }
    g1:
      move_energy:   { name: g1 move energy }
      still_energy:  { name: g1 still energy }
    g2:
      move_energy:   { name: g2 move energy }
      still_energy:  { name: g2 still energy }
    g3:
      move_energy:   { name: g3 move energy }
      still_energy:  { name: g3 still energy }
    g4:
      move_energy:   { name: g4 move energy }
      still_energy:  { name: g4 still energy }
    g5:
      move_energy:   { name: g5 move energy }
      still_energy:  { name: g5 still energy }
    g6:
      move_energy:   { name: g6 move energy }
      still_energy:  { name: g6 still energy }
    g7:
      move_energy:   { name: g7 move energy }
      still_energy:  { name: g7 still energy }
    g8:
      move_energy:   { name: g8 move energy }
      still_energy:  { name: g8 still energy }

    light:
      name: light
      filters: [ { throttle: 1.5s } ]

binary_sensor:
  - platform: ld2410
    has_target:
      name: Presence
    has_moving_target:
      name: Moving Target
    has_still_target:
      name: Still Target

# ===========================
# Apply bedroom tuning automatically at boot
# ===========================
# Targets:
# - distance_resolution: 0.2m
# - max_move_distance_gate: 3
# - max_still_distance_gate: 3
# - timeout: 45s
# - G0–G3 move 25%, still 35%
# - G4–G8 move/still 95% (ignore far zones)
# - light function: off, light threshold high (255)
# ===========================
on_boot:
  priority: 600
  then:
    - switch.turn_on: engineering_mode
    - delay: 500ms

    # Resolution + ranges + timeout
    - select.set:
        id: sel_distance_resolution
        option: "0.2m"
    - number.set:
        id: num_max_move_gate
        value: 3
    - number.set:
        id: num_max_still_gate
        value: 3
    - number.set:
        id: num_timeout
        value: 45

    # Near gates (G0–G3): sensitive for bed
    - number.set: { id: g0_move_th,  value: 25 }
    - number.set: { id: g1_move_th,  value: 25 }
    - number.set: { id: g2_move_th,  value: 25 }
    - number.set: { id: g3_move_th,  value: 25 }
    - number.set: { id: g0_still_th, value: 35 }
    - number.set: { id: g1_still_th, value: 35 }
    - number.set: { id: g2_still_th, value: 35 }
    - number.set: { id: g3_still_th, value: 35 }

    # Far gates (G4–G8): ignore
    - number.set: { id: g4_move_th,  value: 95 }
    - number.set: { id: g5_move_th,  value: 95 }
    - number.set: { id: g6_move_th,  value: 95 }
    - number.set: { id: g7_move_th,  value: 95 }
    - number.set: { id: g8_move_th,  value: 95 }
    - number.set: { id: g4_still_th, value: 95 }
    - number.set: { id: g5_still_th, value: 95 }
    - number.set: { id: g6_still_th, value: 95 }
    - number.set: { id: g7_still_th, value: 95 }
    - number.set: { id: g8_still_th, value: 95 }

    # Light function OFF and high threshold (no auto lighting)
    - select.set:
        id: sel_light_function
        option: "off"
    - number.set:
        id: num_light_th
        value: 255

    - delay: 500ms
    - switch.turn_off: engineering_mode
